name = "Entropies"
uuid = "ed8fcbec-b94c-44b6-89df-898894ad9591"
authors = "Kristian Agasøster Haaga <kahaaga@gmail.com>, George Datseries <datseris.george@gmail.com>"
repo = "https://github.com/kahaaga/Entropies.jl.git"
version = "0.4.0"

[deps]
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DelayEmbeddings = "1.10"
StaticArrays = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
