name = "Entropies"
uuid = "ed8fcbec-b94c-44b6-89df-898894ad9591"
repo = "https://github.com/kahaaga/Entropies.jl.git"
version = "0.1.0"

[deps]
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"

[compat]
julia = "1"
DelayEmbeddings = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
